version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

  drupal:
    image: drupal:latest
    ports:
      -  8080:80
    volumes:
      - ../recommended-project/web:/var/www/html
      - ../recommended-project/vendor:/opt/drupal/vendor
      - ../recommended-project/composer.json:/opt/drupal/composer.json
      - ../recommended-project/composer.lock:/opt/drupal/composer.lock
    links:
      - db
    environment:
      DRUPAL_DB_HOST: ${DRUPAL_DB_HOST}
      DRUPAL_DB_PORT:  ${DRUPAL_DB_PORT}
      DRUPAL_DB_NAME: ${DRUPAL_DB_NAME}
      DRUPAL_DB_USER: ${DRUPAL_DB_USER}
      DRUPAL_DB_PASSWORD: ${DRUPAL_DB_PASSWORD}
